// Derives the stage's species table from the shipped lorebook.
//
// The stage used to bundle its own copy of the whole lorebook and tell
// species from locations by the `constant` flag - a field that only existed
// in that private copy. The moment the book was re-exported from chub (where
// nothing is constant), every town, item and NPC became a catchable moemon.
//
// So: one source of truth, one rule. A lorebook entry is a moemon if its text
// carries the species type tag ("a Water/Fairy-type girl"), which is exactly
// how the stage reads a species' types anyway. Everything else is scenery.
//
//   yarn sync-lore     # after editing distributables/moemon-lore.json
//
// The build runs this first, so a forgotten sync can't ship.

import {readFile, writeFile} from 'fs/promises';

const LOREBOOK = 'distributables/moemon-lore.json';
const OUTPUT = 'src/assets/moemonSpecies.json';

// "a Water-type girl", "an Ice/Psychic-type girl".
const TYPE_TAG = /\ban? ([A-Za-z]+(?:\/[A-Za-z]+)?)-type girl/;

const TYPES = new Set(['Normal', 'Fire', 'Water', 'Electric', 'Grass', 'Ice', 'Fighting',
    'Poison', 'Ground', 'Flying', 'Psychic', 'Bug', 'Rock', 'Ghost', 'Dragon', 'Dark',
    'Steel', 'Fairy']);

const book = JSON.parse(await readFile(LOREBOOK, 'utf8'));
const entries = Object.values(book.entries ?? {});

const species = [];
const untyped = [];
for (const entry of entries) {
    const match = String(entry.content ?? '').match(TYPE_TAG);
    if (!match) continue;

    const types = match[1].split('/');
    const unknown = types.filter(type => !TYPES.has(type));
    if (unknown.length > 0) {
        untyped.push(`${entry.name}: unknown type ${unknown.join(', ')}`);
        continue;
    }
    species.push({name: entry.name, types});
}

species.sort((left, right) => left.name.localeCompare(right.name));

const duplicates = species
    .map(entry => entry.name.toLowerCase())
    .filter((name, index, all) => all.indexOf(name) !== index);

if (untyped.length > 0 || duplicates.length > 0) {
    console.error('sync-lore: lorebook problems\n  ' + [...untyped,
        ...duplicates.map(name => `${name}: duplicate species entry`)].join('\n  '));
    process.exit(1);
}

await writeFile(OUTPUT, JSON.stringify({
    _comment: 'GENERATED by scripts/sync-lore.mjs from distributables/moemon-lore.json. Do not edit by hand - edit the lorebook and run `yarn sync-lore`.',
    species
}, null, 2) + '\n');

console.log(`\x1b[32m✓\x1b[0m sync-lore: ${species.length} species → ${OUTPUT}`);
